### ISSUE TITLE
loadorder.txt processing inconsistency

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/Buffout4-CLAS#14]
I've noticed an inconsistency with loadorder.txt processing that I can't seem to track down. The most notable differences are that one was from MO2 and the other was from Vortex and also, the working log just had an incomplete plugin section and the non-working one had an empty plugin list. I've attached the logs and load orders I was working with to this report.
[loadorder working.txt](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/10088548/loadorder.working.txt)
[loadorder not working.txt](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/10088549/loadorder.not.working.txt)
[crash-2022-11-25-02-43-50 Grimm.log (not working)](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/10088553/crash-2022-11-25-02-43-50.Grimm.log)
[crash-2022-11-25-02-09-59 94 Green Men in a trenchcoat.log (working, plugin section was there but incomplete)](https://github.com/GuidanceOfGrace/Buffout4-CLAS/files/10088560/crash-2022-11-25-02-09-59.94.Green.Men.in.a.trenchcoat.log)

**Comment by GuidanceOfGrace** [comment]
I think I know what the issue is.
The script checks: **if "[00]" in logtext:**
And logtext is the entire text in the crash log. But the script should be checking the **plugin_list** variable.

So to keep it consistent and working as intended, it should be **if "[00]" in plugin_list:** instead.
Since plugin_list is the actual list that the script appends plugins to whether or not loadorder.txt is found.

**Comment by GuidanceOfGrace** [comment]
Actually, now we have to use **if any("[00]" in elem for elem in plugin_list):** instead of just if "[00]" in plugin_list:
Don't know if there's a better way of finding any specific string in a list besides doing this or converting the whole list to something else and converting it back afterwards. I'll implement this in a hotfix before the Version 6.xx release.

**Comment by evildarkarchon** [comment]
I couldn't find a better alternative to any(), so that's what I'd go with.
